site_name: My Personal KB
site_url: https://mrhockeymonkey.github.io/
site_author: Scott Matthews
repo_url: https://github.com/mrhockeymonkey/mrhockeymonkey.github.io
theme:
  name: material
  palette:
    primary: indigo
    accent: purple
  icon:
    logo: fontawesome/solid/code
  favicon: favicon.ico
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
static_templates:
  - "Powershell/README.md"
# extra_javascript:
#   - highlight.pack.js
#   - config.js
# extra_css:
#   - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css
plugins:
  - search
markdown_extensions:
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: 'docs/'
      check_paths: true
  - pymdownx.mark
  - pymdownx.caret
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  #- Angular: ""
  # - C#:
  #   - Cheatsheet: C#/cheatsheet.md
  #   - LINQ: C#/linq.md
  #   - Delegates: C#/delegates.md
  #   - Patterns: "C#/Patterns/README.md"
  #   - Testing:
  #     - Assertions: C#/Testing/assertions.md
  #     - Moq: C#/Testing/moq.md
  #     - Auto Fixture: C#/Testing/auto-fixture.md
  #     - ASP.NET Tests: C#/Testing/asp-net-tests.md
  #     - AKKA.NET Tests: C#/Testing/akka-net-tests.md
  #   - Collections: "C#/Collections.md"
  #   - Stack vs Heap: "C#/Stack vs Heap.md"
  #   - Hostings: "C#/src/GenericHost/README.md"
  # - Powershell: 
  #   - Overview: "Powershell/README.md"
  #   - Encoding: "Powershell/encoding.md"
  #   - IPAddress: "Powershell/ipaddress-comparison.md"
  # #- Python: ""
  # - Theory:
  #   - Conversion: Theory/conversion.md
  #   - Data Structures: Theory/data-structures.md
  #   - Principles: Theory/principles.md
  #   - Sorting Algorithms: Theory/sorting-algorithm.md
  #   - Tree Structures: Theory/tree-structures.md

  - Angular:
    - calling-APIs: "Angular/calling-APIs.md"
    - cheatsheet: "Angular/cheatsheet.md"
    - lazy-loading: "Angular/lazy-loading.md"
    - routing: "Angular/routing.md"
    - rxjs: "Angular/rxjs.md"
    - syntax: "Angular/syntax.md"
  - Bash:
    - Cheatsheet: "Bash/Cheatsheet.md"
  - C#:
    - asynchrony: "C#/asynchrony.md"
    - cheatsheet: "C#/cheatsheet.md"
    - Collections: "C#/Collections.md"
    - delegates: "C#/delegates.md"
    - EF: "C#/EF"
    - Core: "Core.md"
    - linq: "C#/linq.md"
    - project-file: "C#/project-file.md"
    - spans: "C#/spans.md"
    - stack-vs-heap: "C#/stack-vs-heap.md"
    - Testing:
      - akka-net-tests: "C#/Testing/akka-net-tests.md"
      - asp-net-tests: "C#/Testing/asp-net-tests.md"
      - assertions: "C#/Testing/assertions.md"
      - auto-fixture: "C#/Testing/auto-fixture.md"
      - moq: "C#/Testing/moq.md"
  - Docker:
    - Centos: "Docker/Centos.md"
    - README: "Docker/README.md"
  - Kerberos:
    - linux-setup: "Kerberos/linux-setup.md"
    - README: "Kerberos/README.md"
  - Misc:
    - README: "Misc/README.md"
    - DIY:
      - painting: "Misc/DIY/painting.md"
  - Powershell:
    - encoding: "Powershell/encoding.md"
    - ipaddress-comparison: "Powershell/ipaddress-comparison.md"
    - README: "Powershell/README.md"
  - Prometheus:
    - notes: "Prometheus/notes.md"
  - Theory:
    - conversion: "Theory/conversion.md"
    - data-structures: "Theory/data-structures.md"
    - principles: "Theory/principles.md"
    - sorting-algorithm: "Theory/sorting-algorithm.md"
    - tree-structures: "Theory/tree-structures.md"
