site_name: My Personal KB
site_url: https://mrhockeymonkey.github.io/
site_author: Scott Matthews
theme:
  name: material
  icon:
    logo: fontawesome/solid/code
  favicon: favicon.ico
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
extra_css:
  - extra.css
plugins:
  - search
markdown_extensions:
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: 'docs/'
      check_paths: true
  - pymdownx.mark
  - pymdownx.caret
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - C#:
    - Asynchrony: "C#/Asynchrony.md"
    - Cheatsheet: "C#/Cheatsheet.md"
    - Collections: "C#/Collections.md"
    - Delegates: "C#/Delegates.md"
    - Equality: "C#/Equality.md"
    - Linq: "C#/Linq.md"
    - Project File: "C#/Project File.md"
    - Spans: "C#/Spans.md"
    - Stack vs Heap: "C#/Stack vs Heap.md"
    - Libs:
      - EF Core: "C#/Libs/EF Core.md"
    - Testing:
      - Akka.net Tests: "C#/Testing/Akka.net Tests.md"
      - ASP.net Tests: "C#/Testing/ASP.net Tests.md"
      - Assertions: "C#/Testing/Assertions.md"
      - Auto Fixture: "C#/Testing/Auto Fixture.md"
      - Moq: "C#/Testing/Moq.md"
  - Powershell:
    - Encoding: "Powershell/Encoding.md"
    - IP Address Comparison: "Powershell/IP Address Comparison.md"
    - README: "Powershell/README.md"
  - Theory:
    - Closure: "Theory/Closure.md"
    - Conversion: "Theory/Conversion.md"
    - Data Structures: "Theory/Data Structures.md"
    - Principles: "Theory/Principles.md"
    - Sorting Algorithm: "Theory/Sorting Algorithm.md"
    - Tree Structures: "Theory/Tree Structures.md"
  - Etc:
    - Bash:
      - Cheatsheet: "Bash/Cheatsheet.md"
    - Docker:
      - Centos: "Docker/Centos.md"
      - README: "Docker/README.md"
    - Angular:
      - Calling APIs: "Angular/Calling APIs.md"
      - Cheatsheet: "Angular/Cheatsheet.md"
      - Lazy Loading: "Angular/Lazy Loading.md"
      - Routing: "Angular/Routing.md"
      - Rxjs: "Angular/Rxjs.md"
      - Syntax: "Angular/Syntax.md"
    - Coffee:
      - README: "Coffee/README.md"
    - DIY:
      - painting: "DIY/painting.md"
    - Kerberos:
      - Linux Setup: "Kerberos/Linux Setup.md"
      - README: "Kerberos/README.md"
    - Prometheus:
      - Notes: "Prometheus/Notes.md"
    - Helm:
      - README: "Helm/README.md"
