site_name: My Personal KB
site_url: https://mrhockeymonkey.github.io/
site_author: Scott Matthews
repo_url: https://github.com/mrhockeymonkey/mrhockeymonkey.github.io
theme:
  name: material
  palette:
    primary: indigo
    accent: purple
  icon:
    logo: fontawesome/solid/code
  favicon: favicon.ico
  features:
    # - navigation.instant
    #- navigation.sections
    - navigation.tabs
extra_javascript:
  - highlight.pack.js
  - config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css
plugins:
  - search
markdown_extensions:
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.mark
  - pymdownx.caret
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # - Angular: ""
  # - Docker: ""
  # - Kerberos: ""
  # - Theory:
  #   - Principles: "Theory/Principles.md"
nav:
  - C#:
    - Patterns: "C#/Patterns/README.md"
    - Testing:
      - Assertions: C#/Testing/assertions.md
      - Moq: C#/Testing/moq.md
      - Auto Fixture: C#/Testing/auto-fixture.md
    - Collections: "C#/Collections.md"
    - Stack vs Heap: "C#/Stack vs Heap.md"
